language: php

php:
  - 7.4
  - 8.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit
  - composer run ci